scert/scert/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^tt/', include('teachertraining.urls')),
    url(r'^admin/', admin.site.urls),
]

scert/teachertraining/urls.py
from django.conf.urls import url

from . import views

app_name = 'teachertraining'
urlpatterns = [
    url(r'^$', views.mainpage, name='mainpage'),
    url(r'^login/', views.loginx, name='login'),
    url(r'^home/', views.home, name='home'),    
    url(r'^trainingDetails/', views.trainingDetails, name='trainingDetails'),
    url(r'^AssignTraining/(?P<prk>[a-zA-z0-9]*)', views.AssignTraining, name='assignTraining'),
    url(r'^RegisterTraining/', views.RegisterTraining, name='RegisterTraining'),    
    url(r'^InProgressTraining/', views.InProgressTraining, name='InProgressTraining'),    
    url(r'^CompletedTraining/', views.CompletedTraining, name='CompletedTraining'),            
    url(r'^Profile/', views.Profile, name='Profile'),                
    url(r'^WorklistTrainings/(?P<prk>[a-zA-z0-9]*)', views.WorklistTrainings, name='WorklistTrainings'),                    
    url(r'^WorklistTrainingDetail/(?P<prk>[a-zA-z0-9]*)', views.WorklistTrainingDetail, name='WorklistTrainingDetail'),                        
    url(r'^validate_Teachers/(?P<prk>[a-zA-z0-9]*)', views.validate_Teachers, name='validate_Teachers'),                        
    url(r'^Worklist', views.Worklist, name='Worklist'),                    
    url(r'^Logout/', views.Logout, name='Logout'),      
    url(r'^AddTraining/', views.AddTraining, name='AddTraining'),          
    url(r'^AddTrainingPlan/', views.AddTrainingPlan, name='AddTrainingPlan'),          
    url(r'^Register/(?P<prk>[a-zA-z0-9]*)', views.Register, name='Register'),                
    url(r'^RegisterFromWorklist/(?P<prk>[a-zA-z0-9]*)', views.RegisterFromWorklist, name='RegisterFromWorklist'),                    
    url(r'^TeachersEnrolled/(?P<prk>[a-zA-z0-9]*)', views.TeachersEnrolled, name='TeachersEnrolled'),    
    url(r'^CompletePrerequisites/(?P<prk>[a-zA-z0-9]*)', views.CompletePrerequisites, name='CompletePrerequisites'),       
    url(r'^CompletePostrequisites/(?P<prk>[a-zA-z0-9]*)', views.CompletePostrequisites, name='CompletePostrequisites'),           
    url(r'^ApproveRegistration/', views.ApproveRegistration, name='ApproveRegistration'),  
    url(r'^ReviewPreRequisite/', views.ReviewPreRequisite, name='ReviewPreRequisite'),  
    url(r'^TeachersEnquiry/', views.TeachersEnquiry, name='TeachersEnquiry'),    
    url(r'^TrainingEnquiry/', views.TrainingEnquiry, name='TrainingEnquiry'),    
    url(r'^AllTrainings/', views.AllTrainings, name='AllTrainings'),    
    url(r'^submitPrerequisite/(?P<prk>[a-zA-z0-9]*)', views.submitPrerequisite, name='submitPrerequisite'),    
    url(r'^TeacherSubmitsPrerequisite/(?P<prk>[a-zA-z0-9]*)', views.TeacherSubmitsPrerequisite, name='TeacherSubmitsPrerequisite'),        
    url(r'^TeacherSubmitsPostrequisite/(?P<prk>[a-zA-z0-9]*)', views.TeacherSubmitsPostrequisite, name='TeacherSubmitsPostrequisite'),            
    url(r'^MoveToMainTraining/(?P<prk>[a-zA-z0-9]*)', views.MoveToMainTraining, name='MoveToMainTraining'),            
    url(r'^MoveToPost/(?P<prk>[a-zA-z0-9]*)', views.MoveToPost, name='MoveToPost'),                
    url(r'^MoveToComplete/(?P<prk>[a-zA-z0-9]*)', views.MoveToComplete, name='MoveToComplete'),                    
]

scert/teachertraining/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    empId = models.IntegerField(unique=True)
    aadhar_no = models.IntegerField(unique=True)
    age = models.IntegerField()
    joining_date = models.DateField('joining date')
    last_promotion_date = models.DateField('last promotion date')
    subject = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    phone = models.IntegerField()
    def __str__(self):
        return '%s' % (self.name)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if not sender.is_superuser:
            if created:
                print 'not a superuser'
                Teacher.objects.create(user=instance)
            else:
                instance.teacher.save()


class TrainingPlan(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateField('training plan start date')
    end_date = models.DateField('training plan end date')
    def __str__(self):
        return '%s' % (self.name)        

class Training(models.Model):
    name = models.CharField(max_length=200)
    duration = models.IntegerField()
    type_of_training = models.CharField(max_length=200)
    subject = models.CharField(max_length=200)
    def __str__(self):
        return '%s' % (self.name)
    
class TrainingPlanDetail(models.Model):
    FundingSource1 = 'FS1'
    FundingSource2 = 'FS2'
    FundingSource3 = 'FS3'
    FundingSource4 = 'FS4'
    FUNDING_SOURCE = (
        (FundingSource1, 'FundSource1'),
        (FundingSource2, 'FundSource2'),
        (FundingSource3, 'FundSource3'),
        (FundingSource4, 'FundSource4'),
    )
    traininPlanId = models.ForeignKey(TrainingPlan, on_delete=models.CASCADE)
    traingId = models.ForeignKey(Training, on_delete=models.CASCADE)
    fundingSource = models.CharField(
        max_length = 3,
        choices = FUNDING_SOURCE,
        default = FundingSource1,
    )
    start_date = models.DateField('training start date')
    end_date = models.DateField('training end date')
    def __str__(self):
        return '%s' %(self.traingId)
    


class Prerequisite(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    TrainingId = models.ForeignKey(Training, on_delete=models.CASCADE)

class Postrequisite(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    TrainingId = models.ForeignKey(Training, on_delete=models.CASCADE)
    
    
class TrainingPlanEnrollment(models.Model):
    INITIAL = 'INITIAL'
    SUBMITTED = 'SUBMITTED'
    APPROVED = 'APPROVED'
    REQUISITE_STATUS = (
        (INITIAL, 'Initial'),
        (SUBMITTED, 'Submitted'),
        (APPROVED, 'Approved'),
    )
    NOMINATED = 'NOMINATED'
    REGISTRATIONDONE = 'REGISTRATIONDONE'
    PRETRAININGREQUISITE = 'PRE-REQUISITE'
    MAINTRAINING = 'MAINTRAINING'
    POSTTRAININGREQUISITE = 'POST-REQUISITE'
    COMPLETE = 'COMPLETE'
    DISQUALIFIED = 'DISQUALIFIED'
    TRAINING_STATUS = (
        (NOMINATED, 'Nominated'),
        (REGISTRATIONDONE, 'RegistrationDone'),
        (PRETRAININGREQUISITE, 'PreTrainingRequisite'),
        (MAINTRAINING, 'MainTraining'),
        (POSTTRAININGREQUISITE, 'PostTrainingRequisite'),
        (COMPLETE, 'Complete'),
        (DISQUALIFIED, 'Disqualified'),
    )
    trainingPlanDetailId = models.ForeignKey(TrainingPlanDetail, on_delete=models.CASCADE)
    teacherId = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    trainingStatus = models.CharField(
        max_length = 16,
        choices = TRAINING_STATUS,
        default = NOMINATED,
    )
    TrainingPrerequisiteStatus = models.CharField(
        max_length = 9,
        choices = REQUISITE_STATUS,
        default = INITIAL,
    )
    TrainingPostrequisiteStatus = models.CharField(
        max_length = 9,
        choices = REQUISITE_STATUS,
        default = INITIAL,
    )    
    class Meta:
        unique_together = ('teacherId', 'trainingPlanDetailId')

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{}/{1}'.format(instance.user.id,'pre', filename)

class TrainingPrerequisiteStatus(models.Model):
    TrainingStatusId = models.ForeignKey(TrainingPlanEnrollment, on_delete=models.CASCADE)
    TrainingPrerequisiteId = models.ForeignKey(Prerequisite, on_delete=models.CASCADE)
    file = models.FileField(upload_to=user_directory_path)


class TrainingPrerequisiteComments(models.Model):
    TrainingPrerequisiteStatusId = models.ForeignKey(TrainingPrerequisiteStatus, on_delete=models.CASCADE)
    comment = models.CharField(max_length = 200)
    

def user_directory_path_post(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{}/{1}'.format(instance.user.id,'post', filename)

class TrainingPostrequisiteStatus(models.Model):
    TrainingStatusId = models.ForeignKey(TrainingPlanEnrollment, on_delete=models.CASCADE)
    TrainingPostrequisiteId = models.ForeignKey(Postrequisite, on_delete=models.CASCADE)
    file = models.FileField(upload_to=user_directory_path_post)

class TrainingPostrequisiteComments(models.Model):
    TrainingPostrequisiteStatusId = models.ForeignKey(TrainingPostrequisiteStatus, on_delete=models.CASCADE)
    comment = models.CharField(max_length = 200)

scert/teachertraining/forms.py
from django import forms
from django.forms import ModelForm
from models import Training,TrainingPlan, TrainingPlanDetail

class TrainingForm(ModelForm):
    class Meta:
    	model = Training
    	fields = '__all__'

class TrainingPlanForm(ModelForm):
    class Meta:
    	model = TrainingPlan
    	fields = '__all__'


scert/templates/AdminAddTrainings.html
{% extends 'BaseAdminLogin.html' %}


{%block content%}
<!-- Container (The Band Section) -->
<div class="container ">


    <form action="/tt/AddTraining/" method="POST">
        {% csrf_token %}


        {{form.as_ul}}
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Save</button>
    </div>
  </div>
</form>

</div>

{%endblock%}

scert/templates/AdminAllTrainings.html
{% extends 'BaseAdminLogin.html' %}


{%block content%}
<!-- Container (The Band Section) -->
<style type="text/css">
	table.dataTable.select tbody tr,
table.dataTable thead th:first-child {
  cursor: pointer;
}
</style>>
<script>
$(document).ready(function() {

    $('.table').DataTable( {
        columnDefs: [ {
            orderable: false,
            targets:   0
        } ],
        order: [[ 1, 'asc' ]]
    } );
    });
</script>
<div class="container " style="padding-top: 25px;padding-bottom: 10px">
<div class="well well-sg" style="height: 60px;text-align: center;margin-bottom: 0px" >
          <h3>ALL TRAININGS</h3>
</div>
</div>
<div class="container" style="padding-top: 0px">
  <table class="table table-bordered table-striped table-hover" >
      <thead>
      <tr>
      <th>TRAINING ID</th>
        <th>TRAINING NAME</th>
        <th>TRAINING DURATION</th>
        <th>TRAINING TYPE</th>       
        <th>FUNDING SUBJECT</th>        
      </tr>
    </thead>
    <tbody>
{%for itr in lAll%}
      <tr>
        <td>{{itr.id}}</td>
        <td>{{itr.name}}</td>
        <td>{{itr.duration}}</td>
        <td>{{itr.type}}</td>
        <td>{{itr.subject}}</td>
      </tr>      
{%endfor%}

  </table>  
</div>
{%endblock%}

scert/templates/AdminLogin.html
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Theme Made By www.w3schools.com - No Copyright -->
  <title>SCERT</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
  body {
      font: 400 15px/1.8 Lato, sans-serif;
      color: #777;
  }
  h3, h4 {
      margin: 10px 0 30px 0;
      letter-spacing: 5px;
      font-size: 20px;
      color: #111;
  }
  .container {
      padding: 80px 120px;
  }
  .person {
      border: 10px solid transparent;
      margin-bottom: 25px;
      width: 80%;
      height: 80%;
      opacity: 0.7;
  }
  .person:hover {
      border-color: #f1f1f1;
  }
  .carousel-inner img {
      -webkit-filter: grayscale(90%);
      filter: grayscale(90%); /* make all photos black and white */
      width: 100%; /* Set width to 100% */
      margin: auto;
  }
  .carousel-caption h3 {
      color: #fff !important;
  }
  @media (max-width: 600px) {
    .carousel-caption {
      display: none; /* Hide the carousel text when the screen is less than 600 pixels wide */
    }
  }
  .bg-1 {
      background: #2d2d30;
      color: #bdbdbd;
  }
  .bg-1 h3 {color: #fff;}
  .bg-1 p {font-style: italic;}
  .list-group-item:first-child {
      border-top-right-radius: 0;
      border-top-left-radius: 0;
  }
  .list-group-item:last-child {
      border-bottom-right-radius: 0;
      border-bottom-left-radius: 0;
  }
  .thumbnail {
      padding: 0 0 15px 0;
      border: none;
      border-radius: 0;
  }
  .thumbnail p {
      margin-top: 15px;
      color: #555;
  }
  .btn {
      padding: 10px 20px;
      background-color: #333;
      color: #f1f1f1;
      border-radius: 0;
      transition: .2s;
  }
  .btn:hover, .btn:focus {
      border: 1px solid #333;
      background-color: #fff;
      color: #000;
  }
  .modal-header, h4, .close {
      background-color: #333;
      color: #fff !important;
      text-align: center;
      font-size: 30px;
  }
  .modal-header, .modal-body {
      padding: 40px 50px;
  }
  .nav-tabs li a {
      color: #777;
  }
  #googleMap {
      width: 100%;
      height: 400px;
      -webkit-filter: grayscale(100%);
      filter: grayscale(100%);
  }
  .navbar {
      font-family: Montserrat, sans-serif;
      margin-bottom: 0;
      background-color: #2d2d30;
      border: 0;
      font-size: 11px !important;
      letter-spacing: 4px;
      opacity: 0.9;
  }
  .navbar li a, .navbar .navbar-brand {
      color: #d5d5d5 !important;
  }
  .navbar-nav li a:hover {
      color: #fff !important;
  }
  .navbar-nav li.active a {
      color: #fff !important;
      background-color: #29292c !important;
  }
  .navbar-default .navbar-toggle {
      border-color: transparent;
  }
  .open .dropdown-toggle {
      color: #fff;
      background-color: #555 !important;
  }
  .dropdown-menu li a {
      color: #000 !important;
  }
  .dropdown-menu li a:hover {
      background-color: red !important;
  }
  footer {
      position: fixed;
      bottom: 0;
      width: 100%;
      background-color: #2d2d30;
      color: #f5f5f5;
      padding: 22px;
  }
  footer a {
      color: #f5f5f5;
  }
  footer a:hover {
      color: #777;
      text-decoration: none;
  }

  .form-control {
      border-radius: 0;
  }
  textarea {
      resize: none;
  }
  div.transbox {
  margin: 30px;
  background-color: #ffffff;
  border: 1px solid black;
  opacity: 0.6;
  filter: alpha(opacity=60); /* For IE8 and earlier */
}

div.transbox p {
  margin: 5%;
  font-weight: bold;
  color: #000000;
}
  .bg-3 {
      background-color: grey; /* White */
      color: #555555;
  }
  </style>
</head>
<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="50">

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#myPage">SCERT</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#myPage">HOME</a></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">TEACHER TRAINING
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">TRAININGS</a></li>
            <li><a href="#">TRAINING PLAN</a></li>
            <li><a href="#">TEACHER ENROLLMENTS</a></li>
          </ul>
        </li>
        <li><a href="#tour">WORKLIST</a></li>
        <li><a href="#tour">Logout</a></li>
      </ul>
    </div>
  </div>
</nav>


<!-- Container (The Band Section) -->
<div id="band" class="container text-center">
  <h3>MANAGE TEACHERS TRAINING</h3>
  <p>Create trainings, training plans, view teacher enrollments.</p>
  <br>
  <div class="row">
    <div class="col-sm-4 bg-3" id="tets">
      <a href="/tt/trainingDetails/">
        <div class="transbox">
          <p>TRAININGS</p>
        </div>
      </a>
    </div>
    <div class="col-sm-4 bg-3" id="tets">
      <a href="/tt/trainingDetails/">
        <div class="transbox">
          <p>TRAINING PLANS</p>
        </div>
      </a>
    </div>
    <div class="col-sm-4 bg-3" id="tets">
      <a href="/tt/trainingDetails/">
        <div class="transbox">
          <p>TEACHER ENROLLMENTS</p>
        </div>
      </a>
    </div>
  </div>
</div>
<!-- Footer -->
<footer class="text-center">
  <a class="up-arrow" href="#myPage" data-toggle="tooltip" title="TO TOP">
    <span class="glyphicon glyphicon-chevron-up"></span>
  </a>
  <p>SCERT</p>
</footer>


</body>
</html>

scert/templates/AdminTeacherEnquiryDetails.html
{% extends 'BaseAdminLogin.html' %}


{%block content%}
<!-- Container (The Band Section) -->
<style type="text/css">
	table.dataTable.select tbody tr,
table.dataTable thead th:first-child {
  cursor: pointer;
}
</style>>
<script>
$(document).ready(function() {

    $('.table').DataTable( {
        columnDefs: [ {
            orderable: false,
            targets:   0
        } ],
        order: [[ 1, 'asc' ]]
    } );
    });
</script>
<div class="container " style="padding-top: 25px;padding-bottom: 10px">
<div class="well well-sg" style="height: 60px;text-align: center;margin-bottom: 0px" >
          <h3>TEACHER TRAINING DETAILS</h3>
</div>
  <form action="{% url 'teachertraining:TeachersEnquiry' %}" method="POST" ><br>
  {% csrf_token %}
  Employee id of Teacher:
    <input name="teacher_empId">
    <input type="submit" value="submit">
  </form>
</div>
<div class="container" style="padding-top: 0px">
  <table class="table table-bordered table-striped table-hover" >
      <thead>
      <tr>
      <th>TRAINING ID</th>
        <th>TRAINING NAME</th>
        <th>STATUS</th>
        <th>TRAINING TYPE</th>
        <th>START DATE</th>
        <th>ENDING DATE </th>
        <th>TRAINING PLAN</th>       
        <th>FUNDING SOURCE</th>        
      </tr>
    </thead>
    <tbody>
{%for itr in tpe%}
      <tr>
        <td>{{itr.trainingPlanDetailId.traingId.id}}</td>
        <td>{{itr.trainingPlanDetailId.traingId.name}}</td>
        <td>{{itr.trainingStatus}}</td>
        <td>{{itr.trainingPlanDetailId.traingId.type}}</td>
        <td>{{itr.trainingPlanDetailId.start_date}}</td>
        <td>{{itr.trainingPlanDetailId.end_date}}</td>
        <td>{{itr.trainingPlanDetailId.traininPlanId.name}}</td>
        <td>{{itr.trainingPlanDetailId.fundingSource}}</td>
      </tr>      
{%endfor%}

  </table>  
</div>
{%endblock%}

scert/templates/AdminTrainingEnquiryDetails.html
{% extends 'BaseAdminLogin.html' %}


{%block content%}
<!-- Container (The Band Section) -->
<style type="text/css">
	table.dataTable.select tbody tr,
table.dataTable thead th:first-child {
  cursor: pointer;
}
</style>>
<script>
$(document).ready(function() {

    $('.table').DataTable( {
        columnDefs: [ {
            orderable: false,
            targets:   0
        } ],
        order: [[ 1, 'asc' ]]
    } );
    });
</script>
<div class="container " style="padding-top: 25px;padding-bottom: 10px">
<div class="well well-sg" style="height: 60px;text-align: center;margin-bottom: 0px" >
          <h3>TRAINING DETAILS</h3>
</div>
  <form action="{% url 'teachertraining:TrainingEnquiry' %}" method="POST" ><br>
  {% csrf_token %}
  Training id:
    <input name="training_id">
    <input type="submit" value="submit">
  </form>
</div>
<div class="container" style="padding-top: 0px; font-size: 11px">
  <table class="table table-bordered table-striped table-hover" >
      <thead>
      <tr>
      <th>EMPID</th>
      <th>AGE</th>
      <th>JOINING DATE</th>
      <th>LAST PROMOTION DATE</th>
      <th>SUBJECT</th>
        <th>TRAINING STATUS</th>
        <th>DATE STARTED</th>
        <th>ENDING DATE </th>
        <th>TRAINING PLAN</th>       
        <th>FUNDING SOURCE</th>        
      </tr>
    </thead>
    <tbody>
{%for itr in tpd%}
{%for itr1 in itr.trainingplanenrollment_set.all%}
      <tr>
        <td>{{itr1.teacherId.empId}}</td>
        <td>{{itr1.teacherId.age}}</td>
        <td>{{itr1.teacherId.joining_date}}</td>        
        <td>{{itr1.teacherId.last_promotion_date}}</td>        
        <td>{{itr1.teacherId.subject}}</td>        
        <td>{{itr1.trainingStatus}}</td>
        <td>{{itr1.trainingPlanDetailId.start_date}}</td>
        <td>{{itr1.trainingPlanDetailId.end_date}}</td>
        <td>{{itr1.trainingPlanDetailId.traininPlanId.name}}</td>
        <td>{{itr1.trainingPlanDetailId.fundingSource}}</td>
      </tr>      
{%endfor%}
{%endfor%}
  </table>  
</div>
{%endblock%}

scert/templates/AdminWorklistTree.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>jsTree test</title>
  <!-- 2 load the theme CSS file -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/themes/default/style.min.css" />
</head>
<body>
  <!-- 3 setup a container element -->
  <div id="jstree">
    <!-- in this example the tree is populated from inline HTML -->
    {%for te in lTrainingPlanItr%}
    <ul>
      <li>{{te.name}}
        <ul>
                      {%for lte in te.trainingplandetail_set.all%}

                         <li id="child_node_{{te.id}}">{{lte.traingId.name}}</li>
                      {%endfor%}
        </ul>
      </li>
    </ul>
    {%endfor%}
  </div>
  <button>demo button</button>

  <!-- 4 include the jQuery library -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.1/jquery.min.js"></script>
  <!-- 5 include the minified jstree source -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/jstree.min.js"></script>
  <script>
  $(function () {
    // 6 create an instance when the DOM is ready
    $('#jstree').jstree();
    // 7 bind to events triggered on the tree
    $('#jstree').on("changed.jstree", function (e, data) {
      console.log(data.selected);
    });
    // 8 interact with the tree - either way is OK
    $('button').on('click', function () {
      $('#jstree').jstree(true).select_node('child_node_1');
      $('#jstree').jstree('select_node', 'child_node_1');
      $.jstree.reference('#jstree').select_node('child_node_1');
    });
  });
  </script>
</body>
</html>




scert/templates/TeacherRegisterTraining.html
{% extends 'BaseTeacherLogin.html' %}


{%block content%}
<!-- Container (The Band Section) -->
<div class="container" style="padding-top: 25px;padding-bottom: 10px;margin-top: 10px;">
    <div class="well well-sg" style="height: 60px;text-align: center;margin-bottom: 0px">
          <h3 style="letter-spacing: 0px">{{heading}} <b>{{training}} </b></h3>
    </div>
    </div>
    <div class="container">
  <table class="table table-striped table-bordered table-hover">
      <thead>
      <tr>
        <th>TRAINING</th>
        <th>START DATE</th>
        <th>END DATE</th>
{%if whichTraining == "register"%}        
        <th>REGISTER</th>       
{%endif%}         
      </tr>
    </thead>
{%for te in trainings%}
{%if whichTraining == "register"%}
{%if te.trainingStatus == te.NOMINATED%}
 
      <tbody>
      <tr class="success">
        <td>{{te.trainingPlanDetailId.traingId.name}}</td>
        <td>{{te.trainingPlanDetailId.start_date}}</td>
        <td>{{te.trainingPlanDetailId.end_date}}</td>
        <td><a href="{% url 'teachertraining:Register' te.id%}">Register</a></td>
      </tr>      
    </tbody>
{%endif%}
{%elif whichTraining == "inProgress"%}
{%if te.trainingStatus != te.COMPLETE%}
  
      <tbody>
      <tr class="success">
        <td>{{te.trainingPlanDetailId.traingId.name}}</td>
        <td>{{te.trainingPlanDetailId.start_date}}</td>
        <td>{{te.trainingPlanDetailId.end_date}}</td>
      </tr>      
    </tbody>
{%endif%}
{%elif whichTraining == "complete"%}
{%if te.trainingStatus == te.COMPLETE%}
      <tbody>
      <tr class="success">
        <td>{{te.trainingPlanDetailId.traingId.name}}</td>
        <td>{{te.trainingPlanDetailId.start_date}}</td>
        <td>{{te.trainingPlanDetailId.end_date}}</td>
      </tr>      
    </tbody>
{%endif%}
{%endif%}
{%endfor%}
  </table>
</div>

{%endblock%}

scert/templates/TeacherRegisterTrainingFailed.html

{% extends 'BaseTeacherLogin.html' %}


{%block content%}
<!-- Container (The Band Section) -->
<div id="band" class="container text-center">
  <div class="row">
    <div class="well">
          <p>{{heading}}</p>
    </div>
  </div>
</div>
{%endblock%}



